=== Kaushal0987/HTML/php/xml/purchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="purchaseOrder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="order" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="poid" type="xs:integer" use="required"/>
            <xs:element name="orderDate" type="xs:string"/>
            <xs:element name="shippingAddress">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="houseNumber" type="xs:string"/>
                  <xs:element name="streetName" type="xs:string"/>
                  <xs:element name="city" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="billingAddress">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="houseNumber" type="xs:string"/>
                  <xs:element name="streetName" type="xs:string"/>
                  <xs:element name="city" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="items" minOccurs="1" maxOccurs="20">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="item" minOccurs="1" maxOccurs="20">
                    <xs:complexType>
                      <xs:attribute name="itemId" type="xs:integer" use="required"/>
                      <xs:element name="itemName" type="xs:string"/>
                      <xs:element name="quantity" type="xs:integer"/>
                      <xs:element name="price" type="xs:decimal"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Kaushal0987/HTML/php/xml/purchaseOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="purchaseOrder.xsd">

  <order poid="1">
    <orderDate>2023-08-09</orderDate>
    <shippingAddress>
      <houseNumber>123</houseNumber>
      <streetName>Main Street</streetName>
      <city>CityA</city>
    </shippingAddress>
    <billingAddress>
      <houseNumber>456</houseNumber>
      <streetName>Second Street</streetName>
      <city>CityB</city>
    </billingAddress>
    <items>
      <item itemId="101">
        <itemName>ProductA</itemName>
        <quantity>5</quantity>
        <price>99.99</price>
      </item>
      <!-- Add more items here -->
    </items>
  </order>

  <!-- Add more orders here -->

</purchaseOrder>
